### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by kovasnik** [OS-IS/ai202-bogachik#1]

**Comment by kovasnik** [comment]
![image](https://github.com/user-attachments/assets/7a017c85-f7d7-42e5-a142-895a178b5180)

**Comment by kovasnik** [comment]
Нажаль не вдалося з'єднатись з репозиторієм через токен

**Comment by kovasnik** [comment]
![image](https://github.com/user-attachments/assets/4c1279ef-8e72-438b-924f-5d7eb14ea07e)

**Comment by kovasnik** [comment]
![image](https://github.com/user-attachments/assets/3258e037-e99f-4837-832d-362a8f4307e9)  
фрагмент відкриття приватного ключу

**Comment by oleksandrblazhko** [comment]
> ![image](https://private-user-images.githubusercontent.com/79566284/368504564-3258e037-e99f-4837-832d-362a8f4307e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTE3MzYsIm5iZiI6MTcyNjY1MTQzNiwicGF0aCI6Ii83OTU2NjI4NC8zNjg1MDQ1NjQtMzI1OGUwMzctZTk5Zi00ODM3LTgzMmQtMzYyYThmNDMwN2U5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5MjM1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNzQ0ZGViMDg3ZTQxNTc3OTdkZWFlNWJjMDIyY2ZkZjI4N2RjMTcyOTA1MDM5NGMzMWE2MTA0NmZhMTc5ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w8qeiqMg7Xp7dqfo0qcccrMVf6KfSDkxX9narrmSzXY) фрагмент відкриття приватного ключу

Використовуємо відкритий ключ.

**Comment by kovasnik** [comment]
Так зрозумів ось його фрагмент  
![image](https://github.com/user-attachments/assets/2af95e94-38f7-483b-8fa4-ee1d8dfbdeb9)

**Comment by kovasnik** [comment]
Створено ключ:  
![image](https://github.com/user-attachments/assets/60ea804a-f6c5-4635-bdac-0faf4d11e9e0)

**Comment by oleksandrblazhko** [comment]
Перевірте ще разок роботу завдання з токеном.
Але замість імені вашого користувача вкажіть OS-IS

**Comment by kovasnik** [comment]
![image](https://github.com/user-attachments/assets/46bc59ec-4127-41c3-954e-bf10178b6273)  
так дякую все запрацювало

**Comment by oleksandrblazhko** [comment]
Дякую вам за оперативність виконання рішень.

**Comment by kovasnik** [comment]
![image](https://github.com/user-attachments/assets/343e2ec6-3003-4cef-96e3-5abc139a53e2)  
тут також потрібно було замінити користувача

**Comment by oleksandrblazhko** [comment]
> ![image](https://private-user-images.githubusercontent.com/79566284/368514368-343e2ec6-3003-4cef-96e3-5abc139a53e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NTMwMjMsIm5iZiI6MTcyNjY1MjcyMywicGF0aCI6Ii83OTU2NjI4NC8zNjg1MTQzNjgtMzQzZTJlYzYtMzAwMy00Y2VmLTk2ZTMtNWFiYzEzOWE1M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA5NDUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZmQ5Y2U4NmZiNjJhNjFlYzQ3ODYyMjk5Y2Q2ZWVjMmQwYTgyMWE1NTAzZmI5YTUxNjI1Mzc2NDIxZTc2ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BVxgUUiNpnPzCwqCc95Y6dkR_lHTg8on_Xlnl4X3L1w) тут також потрібно було замінити користувача

так, це було 4-те завдання
