### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-bogachik#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
3) Відомо, що Git-система контроля версій використовує запити Pull Request. 
Поясніть, будь ласка, як використання такого запиту може підвищити 
безпеку процесів створення програмного продукту?

**Comment by kovasnik** [comment]
Запити Pull Request дають можливість перевірити код перед злиттям що допомагає знайти помилки в коді які загрожують безпеці проекту. Мінімізує ризик випадкового додавання вразливостей або шкідливого коду. 
GitHub є можливість протестувати код для виявлення помилок безпеки.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
